### ISSUE TITLE
Ingesting data after a crash results in another crash

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#21]
% Loaded DLM: PNG.
% Loaded DLM: JPEG.
% LOADCT: Loading table Rainbow + white
% Loaded DLM: NCDF.
% XMANAGER: Caught unexpected error from client application. Message follows...
% FILE_COPY: Destination file already exists. File: /home/dmarrable/DIMITRI_3.0/Input/Site_DomeC/MERIS/Proc_3rd_Reprocessing/DomeC_MERIS_Proc_3rd_Reprocessing.nc_TEMP_BACKUP.
% Execution halted at:  DIMITRI_INTERFACE_EXTRACT_TOA_NCDF
%                       INGEST_MERIS_PRODUCT
%                       DIMITRI_INTERFACE_INGEST
%                       DHMI_INGEST_PROCESS
%                       XMANAGER_EVLOOP_STANDARD
%                       XMANAGER        
%                       DIMITRI_V3      
%                       IDLRTMAIN       
%                       $MAIN$

**Comment by MArias2014** [comment]
Not surprising. The problem here is when DIMITRI crashes once the files was open but before was closed, which leaves the temp file, and hence, it is not able to handle later this. In general, there are problems when DIMITRI crashes as tends to corrupt the files in which it is working when that happens. By "corrupt" I mean that the user has to remove by hand these incomplete files, and in some cases, as the "per pixel" file from DIMITRI v3, forced to not being able to mend the problem and having to reingest data over that site, sensor and processing, with the consequent loss of time. I think this is still a potential problem in DIMITRI 4 but at different level. DIMITRI lacks of functionality to go backwards and correct errors. In my point of view, fixing this implies a major refactoring of DIMITRI functionalities. This is not a bug but a limitation of the software. I would propose this a further improvement for DIMITRI, but to be discussed.
