### ISSUE TITLE
Ingesting MODISA data over LIbya4 ALL causes DIMITRI to 'hang'

### ISSUE THREAD

**Issue by marrabld** [dimitri-argans/DIMITRI#40]
Choosing ALL makes DIMITRI unresponsive.  But doing year by year seems to work.  Reason could be that on a 4gb DIMITRI uses up all the memory.  Particularly 2004 uses lots of memory.

**Comment by MArias2014** [comment]
The problem was related to the "Per Pixel" datafile. IDL puts all the file in memory before updating it, which means that the use of RAM increases when the file increases its size. This is not a problem meanwhile you do not ingest too many files and the "per pizel" files keeps small. However, due to the density of pixels in MODIS-Aqua, the file gets very huge crashing the memory. The issue was solved in DIMITRI 4, so it is no longer a problem, as know one "per pixel" file is created per product, and hence, no issues with RAM.
